// <auto-generated />
namespace SoftecsulTarGetID.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1000_Inc_CE_PortaComIDterminal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1000_Inc_CE_PortaComIDterminal));
        
        string IMigrationMetadata.Id
        {
            get { return "201812211812259_1000_Inc_CE_PortaComIDterminal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
